version: '3.2'
services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
    - 9090:9090
    network_mode: "host"
    volumes:
    - ./prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
    - infracloudio_csvserver

  infracloudio_csvserver:
    image: infracloudio/csvserver:latest
    container_name: csvserver_container
    ports:
    - 9393:9300
    volumes:
    - ./inputFile:/csvserver/inputdata
    environment:
      CSVSERVER_BORDER: Orange
